# Generated by Django 3.1.7 on 2021-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtIssuer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='time_sent',
            field=models.DateTimeField(),
        ),
    ]
